#undef TAPPING_TERM
#define TAPPING_TERM 150

#define COMBO_TERM 80

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "7OpYb/gaq4Mw"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define RGB_MATRIX_STARTUP_SPD 60

