#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 180

#define PERMISSIVE_HOLD

#define COMBO_TERM 80

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "7OpYb/5WwpQw"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

// Custom qmk changes
#define NO_ALT_REPEAT_KEY
